import React, { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
    Bot, Clock, Settings, Cpu, Plus, Square, X, MessageSquare, Send, CalendarRange, RefreshCw, Zap
} from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

import { useThemeContext } from '../../context/ThemeContext';
import { useSettings } from '../../context/SettingsContext';
import { useNotes } from '../../hooks/useNotes';
import { useTodos } from '../../hooks/useTodos';
import { useHourlyLog } from '../../hooks/useHourlyLog';
import { Preferences } from '@capacitor/preferences';
import { storage } from '../../lib/storage';

import { useAISessions, resetAISessionHistory } from './useAISessions';
import { useAIModels } from './useAIModels';
import { useAICommands } from './useAICommands';
import { useAIEngine } from './useAIEngine';
import { formatChatPrompt } from './promptBuilder';
import { getRelevantContext } from './contextBuilder';
import { canAutoGenerateDigest, generateSummaryDigest, getSummaryWindowContext, loadSummaryDigests, saveSummaryDigests, shouldRefreshDigest, type SummaryDigest } from './summaryDigests';
import { useBatteryStatus } from './useBatteryStatus';

export const resetAIHistory = () => {
    resetAISessionHistory();
};

export const AIView: React.FC = () => {
    const { theme } = useThemeContext();
    const dark = theme === 'dark';
    const { voiceAiChargingEnabled } = useSettings();

    const { notes } = useNotes();
    const { todos, addTodo, toggleTodo, deleteTodo } = useTodos();
    const { addNote, updateNote, deleteNote } = useNotes();
    const todayKey = new Date().toISOString().split('T')[0];
    const { logs: hourlyLogs, saveLog: saveHourlyLog } = useHourlyLog(todayKey);
    const [activeTab, setActiveTab] = useState<'chat' | 'models' | 'settings'>('chat');
    const [inputText, setInputText] = useState('');
    const [isHistoryOpen, setIsHistoryOpen] = useState(false);
    const [persistentMemories, setPersistentMemories] = useState<string[]>([]);
    const [summaryDigests, setSummaryDigests] = useState<SummaryDigest[]>([]);
    const [summaryBusyId, setSummaryBusyId] = useState<string | null>(null);
    const [summaryStatus, setSummaryStatus] = useState('');
    const [aiConfig, setAiConfig] = useState({
        threads: 6,
        use_mmap: true,
        responseType: 'standard' as 'brief' | 'standard' | 'detailed',
        customInstructions: '',
        n_predict: 256,
        temperature: 0.5,
        top_k: 20,
        top_p: 0.85,
        penalty: 1.2,
        disableContext: false,
        directMode: false,
        n_gpu_layers: 0,
        n_ctx: 1280
    });

    const [isMobile, setIsMobile] = useState(window.innerWidth <= 768);
    const { isCharging, isSupported: batterySupported } = useBatteryStatus();
    useEffect(() => {
        const handleResize = () => setIsMobile(window.innerWidth <= 768);
        window.addEventListener('resize', handleResize);
        return () => window.removeEventListener('resize', handleResize);
    }, []);

    useEffect(() => {
        loadSummaryDigests().then(setSummaryDigests).catch((error) => {
            console.error('Failed to load AI summary digests', error);
        });
    }, []);

    const configLoadedRef = useRef(false);
    useEffect(() => {
        Preferences.get({ key: 'ai_persistent_memories' }).then(res => {
            if (res.value) setPersistentMemories(JSON.parse(res.value));
        });
        Preferences.get({ key: 'ai_engine_config' }).then(res => {
            if (res.value) setAiConfig(prev => ({ ...prev, ...JSON.parse(res.value!) }));
            configLoadedRef.current = true;
        });
    }, []);

    useEffect(() => {
        if (!configLoadedRef.current) return;
        Preferences.set({ key: 'ai_engine_config', value: JSON.stringify(aiConfig) });
    }, [aiConfig]);

    const {
        models, loadedModel, isDetecting, handleLoadModel, handleAutoLoad, handleDownload, handleDelete, handleOffload
    } = useAIModels((err: string | null) => console.error("Model Error:", err));

    useEffect(() => {
        if (!isDetecting && !loadedModel && models.some(m => m.status === 'downloaded')) {
            handleAutoLoad(aiConfig);
        }
    }, [isDetecting, loadedModel, models.length]);

    const {
        sessions, setSessions, activeSessionId,
        chatMessages, setChatMessages, activeSessionRef,
        persistSessions, handleNewChat, handleSwitchSession, handleDeleteSession
    } = useAISessions(loadedModel);

    const { parseCommands } = useAICommands(
        todos, notes, persistentMemories,
        addTodo, toggleTodo, deleteTodo,
        addNote, updateNote, deleteNote,
        setPersistentMemories, saveHourlyLog
    );

    useEffect(() => {
        storage.getAISessions().then((loaded: any[]) => {
            if (loaded.length > 0) {
                setSessions(loaded);
                handleNewChat();
            } else {
                handleNewChat();
            }
        });
    }, []);

    const {
        isGenerating, isThinking,
        handleSendMessage, handleStopGeneration
    } = useAIEngine(
        loadedModel, aiConfig, chatMessages, setChatMessages,
        activeSessionId, setSessions, activeSessionRef,
        (input) => getRelevantContext(input, { notes, todos, hourlyLogs, persistentMemories, aiConfig }),
        formatChatPrompt,
        parseCommands,
        persistSessions
    );

    const weeklyContext = getSummaryWindowContext('week', notes);
    const monthlyContext = getSummaryWindowContext('month', notes);
    const digestCards = [
        { context: weeklyContext, digest: summaryDigests.find(item => item.id === weeklyContext.id) },
        { context: monthlyContext, digest: summaryDigests.find(item => item.id === monthlyContext.id) }
    ];
    const isNoteWritingIdle = canAutoGenerateDigest(notes);
    const autoDigestInFlightRef = useRef(false);

    const upsertDigest = async (nextDigest: SummaryDigest) => {
        setSummaryDigests(current => {
            const nextDigests = [
                nextDigest,
                ...current.filter(item => !(item.period === nextDigest.period && item.id === nextDigest.id))
            ].sort((a, b) => b.generatedAt - a.generatedAt);

            void saveSummaryDigests(nextDigests);
            return nextDigests;
        });
    };

    const runDigestGeneration = async (period: 'week' | 'month') => {
        if (!loadedModel) {
            setSummaryStatus('Load a local model to generate readymade summaries.');
            return;
        }

        const context = period === 'week' ? weeklyContext : monthlyContext;
        setSummaryBusyId(context.id);
        setSummaryStatus(`Refreshing ${context.label.toLowerCase()}...`);

        try {
            const nextDigest = await generateSummaryDigest(context, aiConfig);
            await upsertDigest(nextDigest);
            setSummaryStatus(`${context.label} summary is ready to read.`);
        } finally {
            setSummaryBusyId(null);
        }
    };

    const scrollRef = useRef<HTMLDivElement>(null);
    const [isAtBottom, setIsAtBottom] = useState(true);

    const scrollToBottom = (behavior: ScrollBehavior = 'smooth') => {
        if (scrollRef.current) {
            scrollRef.current.scrollTo({ top: scrollRef.current.scrollHeight, behavior });
        }
    };

    useEffect(() => {
        const lastMsg = chatMessages[chatMessages.length - 1];
        if (lastMsg?.sender === 'user') { scrollToBottom('instant'); return; }
        if (isAtBottom) scrollToBottom();
    }, [chatMessages]);

    useEffect(() => {
        if (!isGenerating) scrollToBottom();
    }, [isGenerating]);

    useEffect(() => {
        if (!voiceAiChargingEnabled || !loadedModel || !batterySupported || !isCharging || !isNoteWritingIdle || isGenerating || summaryBusyId) {
            return;
        }

        const staleCard = digestCards.find(({ context, digest }) => shouldRefreshDigest(digest, context));
        if (!staleCard || autoDigestInFlightRef.current) return;

        autoDigestInFlightRef.current = true;
        setSummaryStatus(`Charging mode is preparing your ${staleCard.context.label.toLowerCase()} summary.`);

        generateSummaryDigest(staleCard.context, aiConfig)
            .then(upsertDigest)
            .then(() => {
                setSummaryStatus(`${staleCard.context.label} summary refreshed while charging.`);
            })
            .finally(() => {
                autoDigestInFlightRef.current = false;
            });
    }, [voiceAiChargingEnabled, loadedModel, batterySupported, isCharging, isNoteWritingIdle, digestCards, aiConfig, isGenerating, summaryBusyId]);

    // Settings card shared style
    const settingsCard: React.CSSProperties = {
        padding: '1rem',
        background: dark ? 'linear-gradient(180deg, rgba(15,23,42,0.72), rgba(17,24,39,0.82))' : 'rgba(255,255,255,0.92)',
        borderRadius: '20px',
        border: `1px solid ${dark ? 'rgba(148,163,184,0.12)' : 'rgba(99,102,241,0.1)'}`,
        boxShadow: dark ? '0 18px 38px rgba(2,6,23,0.24)' : '0 10px 28px rgba(99,102,241,0.08)',
        backdropFilter: 'blur(18px)',
        WebkitBackdropFilter: 'blur(18px)'
    };

    return (
        <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="ai-container"
            style={{ position: 'fixed', inset: 0, overflow: 'hidden', display: 'flex', flexDirection: 'column',
                background: dark ? 'linear-gradient(180deg, #020617 0%, #0f172a 58%, #111827 100%)' : '#f5f4ff' }}
        >
            {/* Ambient background blobs */}
            <div aria-hidden style={{ position: 'absolute', inset: 0, overflow: 'hidden', pointerEvents: 'none', zIndex: 0 }}>
                <div style={{
                    position: 'absolute', top: '-80px', right: '-80px', width: '480px', height: '480px', borderRadius: '50%',
                    background: dark ? 'radial-gradient(circle, rgba(59,130,246,0.18) 0%, transparent 68%)' : 'radial-gradient(circle, rgba(139,92,246,0.14) 0%, transparent 65%)',
                    filter: 'blur(72px)'
                }} />
                <div style={{
                    position: 'absolute', bottom: '60px', left: '-80px', width: '380px', height: '380px', borderRadius: '50%',
                    background: dark ? 'radial-gradient(circle, rgba(244,114,182,0.12) 0%, transparent 66%)' : 'radial-gradient(circle, rgba(56,189,248,0.1) 0%, transparent 65%)',
                    filter: 'blur(72px)'
                }} />
            </div>

            {/* Header */}
            <header style={{
                padding: '12px 18px', display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                borderBottom: `1px solid ${dark ? 'rgba(148,163,184,0.12)' : 'rgba(99,102,241,0.1)'}`,
                background: dark ? 'rgba(2,6,23,0.72)' : 'rgba(255,255,255,0.88)',
                backdropFilter: 'blur(24px)', WebkitBackdropFilter: 'blur(24px)',
                zIndex: 50, position: 'relative'
            }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                    <button onClick={() => setIsHistoryOpen(true)} style={{
                        background: dark ? 'rgba(15,23,42,0.72)' : 'rgba(99,102,241,0.08)',
                        border: `1px solid ${dark ? 'rgba(148,163,184,0.14)' : 'rgba(99,102,241,0.12)'}`,
                        padding: '7px', borderRadius: '10px',
                        color: dark ? 'rgba(255,255,255,0.55)' : '#6366f1',
                        cursor: 'pointer', display: 'flex'
                    }}>
                        <Clock size={17} />
                    </button>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '7px' }}>
                        <h1 style={{
                            margin: 0, fontSize: '1.2rem', fontWeight: 900, letterSpacing: '-0.3px',
                            background: dark ? 'linear-gradient(135deg, #a78bfa 0%, #38bdf8 100%)' : 'linear-gradient(135deg, #6366f1 0%, #0ea5e9 100%)',
                            WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent'
                        }}>Akitsu</h1>
                        <span style={{
                            width: 7, height: 7, borderRadius: '50%', flexShrink: 0,
                            background: loadedModel ? '#22c55e' : dark ? 'rgba(255,255,255,0.18)' : 'rgba(0,0,0,0.12)',
                            boxShadow: loadedModel ? '0 0 8px rgba(34,197,94,0.75)' : 'none'
                        }} />
                    </div>
                    <button onClick={() => { handleNewChat(); setActiveTab('chat'); }} style={{
                        border: 'none', background: dark ? 'rgba(34,197,94,0.1)' : 'rgba(34,197,94,0.08)', color: '#22c55e',
                        width: '24px', height: '24px', borderRadius: '50%',
                        display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer'
                    }}>
                        <Plus size={14} />
                    </button>
                </div>

                <div style={{
                    display: 'flex', padding: '3px', borderRadius: '13px',
                    background: dark ? 'rgba(15,23,42,0.58)' : 'rgba(99,102,241,0.06)',
                    border: `1px solid ${dark ? 'rgba(148,163,184,0.12)' : 'rgba(99,102,241,0.1)'}`
                }}>
                    <TabButton active={activeTab === 'chat'} onClick={() => setActiveTab('chat')} icon={MessageSquare} label="Chat" dark={dark} />
                    <TabButton active={activeTab === 'models'} onClick={() => setActiveTab('models')} icon={Cpu} label="Models" dark={dark} />
                    <TabButton active={activeTab === 'settings'} onClick={() => setActiveTab('settings')} icon={Settings} label="Engine" dark={dark} />
                </div>
            </header>

            <main style={{ flex: 1, position: 'relative', overflow: 'hidden', zIndex: 1 }}>
                <AnimatePresence mode="wait">

                    {/* ── CHAT TAB ── */}
                    {activeTab === 'chat' && (
                        <motion.div key="chat" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -10 }}
                            style={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
                            <div
                                ref={scrollRef}
                                onScroll={(e) => {
                                    const { scrollTop, scrollHeight, clientHeight } = e.currentTarget;
                                    setIsAtBottom(scrollHeight - scrollTop - clientHeight < 50);
                                }}
                                className="chat-messages dashboard-scrollbar"
                                style={{ flex: 1, overflowY: 'auto', padding: '1.5rem 1.1rem', display: 'flex', flexDirection: 'column', gap: '1rem',
                                    touchAction: 'pan-y', overscrollBehavior: 'contain' }}
                            >
                                <div style={{ display: 'grid', gridTemplateColumns: isMobile ? '1fr' : 'repeat(2, minmax(0, 1fr))', gap: '0.9rem' }}>
                                    {digestCards.map(({ context, digest }) => {
                                        const isRefreshing = summaryBusyId === context.id;
                                        const needsRefresh = shouldRefreshDigest(digest, context);

                                        return (
                                            <SummaryCard
                                                key={context.id}
                                                dark={dark}
                                                contextLabel={context.label}
                                                digest={digest}
                                                noteCount={context.noteCount}
                                                isRefreshing={isRefreshing}
                                                needsRefresh={needsRefresh}
                                                chargingMessage={
                                                    voiceAiChargingEnabled
                                                        ? (batterySupported
                                                            ? (isCharging
                                                                ? (isNoteWritingIdle ? 'Charging mode can refresh this automatically.' : 'Akitsu is waiting until note writing settles before refreshing.')
                                                                : 'Automatic refresh resumes when the device is charging.')
                                                            : 'Charging detection is unavailable here, so you can refresh manually.')
                                                        : 'Enable charging mode in Settings if you want background refresh behavior like Voice Notes.'
                                                }
                                                onRefresh={() => { void runDigestGeneration(context.period); }}
                                                onChat={() => {
                                                    const starter = digest?.chatPrompt || `Help me unpack my ${context.label.toLowerCase()} summary and identify the important next steps.`;
                                                    setInputText(starter);
                                                    scrollToBottom();
                                                }}
                                            />
                                        );
                                    })}
                                </div>

                                {summaryStatus && (
                                    <div style={{
                                        padding: '0.9rem 1rem',
                                        borderRadius: '18px',
                                        background: dark ? 'rgba(15,23,42,0.5)' : 'rgba(255,255,255,0.92)',
                                        border: `1px solid ${dark ? 'rgba(96,165,250,0.14)' : 'rgba(99,102,241,0.12)'}`,
                                        color: dark ? 'rgba(226,232,240,0.78)' : '#52627d',
                                        fontSize: '0.84rem',
                                        lineHeight: 1.6
                                    }}>
                                        {summaryStatus}
                                    </div>
                                )}

                                {chatMessages.length === 0 ? (
                                    <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                                        <div style={{
                                            width: 'min(100%, 560px)', padding: '1.35rem', borderRadius: '30px',
                                            background: dark ? 'linear-gradient(180deg, rgba(15,23,42,0.78), rgba(17,24,39,0.88))' : 'rgba(255,255,255,0.95)',
                                            border: `1px solid ${dark ? 'rgba(148,163,184,0.12)' : 'rgba(99,102,241,0.1)'}`,
                                            boxShadow: dark ? '0 24px 48px rgba(2,6,23,0.28)' : '0 14px 32px rgba(99,102,241,0.08)',
                                            display: 'flex', flexDirection: 'column', gap: '1rem'
                                        }}>
                                            <div style={{ display: 'flex', alignItems: 'center', gap: '0.95rem' }}>
                                                <div style={{
                                                    width: 68, height: 68, borderRadius: '22px',
                                                    background: dark ? 'linear-gradient(135deg, rgba(99,102,241,0.24), rgba(56,189,248,0.18))' : 'rgba(99,102,241,0.08)',
                                                    border: `1px solid ${dark ? 'rgba(148,163,184,0.14)' : 'rgba(99,102,241,0.14)'}`,
                                                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                                                    boxShadow: dark ? '0 20px 32px rgba(30,41,59,0.32)' : '0 0 24px rgba(99,102,241,0.1)'
                                                }}>
                                                    <Bot size={28} color={dark ? '#c4b5fd' : '#6366f1'} strokeWidth={1.6} />
                                                </div>
                                                <div style={{ display: 'flex', flexDirection: 'column', gap: '0.28rem' }}>
                                                    <div style={{ fontSize: '1rem', fontWeight: 800, color: dark ? 'rgba(255,255,255,0.88)' : '#1f2937' }}>Ask Akitsu anything</div>
                                                    <div style={{ fontSize: '0.8rem', color: dark ? 'rgba(226,232,240,0.5)' : '#64748b', lineHeight: 1.5 }}>Chat with your local Qwen model, pull in notes and tasks, and keep everything private on device.</div>
                                                </div>
                                            </div>
                                            <div style={{ display: 'grid', gridTemplateColumns: isMobile ? '1fr' : 'repeat(3, minmax(0, 1fr))', gap: '0.7rem' }}>
                                                {[
                                                    loadedModel ? loadedModel : 'No model loaded',
                                                    `${notes.length} notes available`,
                                                    `${todos.filter((t: any) => !t.completed).length} open tasks`
                                                ].map((item, index) => (
                                                    <div key={index} style={{
                                                        padding: '0.8rem 0.9rem', borderRadius: '18px',
                                                        background: dark ? 'rgba(2,6,23,0.34)' : 'rgba(248,250,252,0.92)',
                                                        border: `1px solid ${dark ? 'rgba(148,163,184,0.1)' : 'rgba(226,232,240,0.9)'}`,
                                                        fontSize: '0.8rem', fontWeight: 700,
                                                        color: dark ? 'rgba(226,232,240,0.84)' : '#334155'
                                                    }}>{item}</div>
                                                ))}
                                            </div>
                                        </div>
                                    </div>
                                ) : (
                                    chatMessages.map((msg) => (
                                        <div key={msg.id} style={{ display: 'flex', flexDirection: 'column', alignItems: msg.sender === 'user' ? 'flex-end' : 'flex-start' }}>
                                            <div style={{
                                                maxWidth: '82%', padding: '11px 16px',
                                                borderRadius: msg.sender === 'user' ? '20px 20px 5px 20px' : '20px 20px 20px 5px',
                                                background: msg.sender === 'user'
                                                    ? 'linear-gradient(135deg, #6366f1, #0ea5e9)'
                                                    : dark ? 'rgba(15,23,42,0.62)' : 'rgba(255,255,255,0.96)',
                                                color: msg.sender === 'user' ? 'white' : dark ? 'rgba(255,255,255,0.88)' : '#1e293b',
                                                border: msg.sender === 'user' ? 'none' : `1px solid ${dark ? 'rgba(167,139,250,0.14)' : 'rgba(226,232,240,0.9)'}`,
                                                boxShadow: msg.sender === 'user'
                                                    ? '0 4px 22px rgba(99,102,241,0.38)'
                                                    : dark ? '0 2px 16px rgba(0,0,0,0.32)' : '0 4px 18px rgba(0,0,0,0.06)',
                                                fontSize: '0.92rem', lineHeight: 1.6
                                            }}>
                                                <ReactMarkdown remarkPlugins={[remarkGfm]}>{msg.text}</ReactMarkdown>
                                            </div>
                                            <div style={{ fontSize: '0.67rem', color: dark ? 'rgba(255,255,255,0.22)' : '#94a3b8', marginTop: '4px', paddingLeft: '4px', paddingRight: '4px', display: 'flex', gap: '8px' }}>
                                                {new Date(msg.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                                                {msg.msPerToken && <span style={{ color: dark ? '#38bdf8' : '#0ea5e9', fontWeight: 700 }}>{msg.msPerToken} ms/tok</span>}
                                            </div>
                                        </div>
                                    ))
                                )}
                                {(isGenerating || isThinking) && <TypingIndicator isThinking={isThinking} dark={dark} />}
                            </div>

                            {/* Input bar */}
                            <div style={{
                                padding: '10px 12px',
                                background: dark ? 'rgba(2,6,23,0.74)' : 'rgba(245,244,255,0.92)',
                                backdropFilter: 'blur(16px)', WebkitBackdropFilter: 'blur(16px)',
                                borderTop: `1px solid ${dark ? 'rgba(255,255,255,0.06)' : 'rgba(99,102,241,0.1)'}`
                            }}>
                                <div style={{
                                    maxWidth: '800px', margin: '0 auto',
                                    background: dark ? 'rgba(15,23,42,0.68)' : 'rgba(255,255,255,0.98)',
                                    padding: '5px 5px 5px 18px', borderRadius: '28px',
                                    border: `1px solid ${dark ? 'rgba(129,140,248,0.22)' : 'rgba(99,102,241,0.18)'}`,
                                    display: 'flex', alignItems: 'center', gap: '10px',
                                    boxShadow: dark ? '0 0 0 1px rgba(129,140,248,0.07), 0 8px 28px rgba(0,0,0,0.35)' : '0 4px 28px rgba(99,102,241,0.12)'
                                }}>
                                    <input
                                        type="text" value={inputText} onChange={e => setInputText(e.target.value)}
                                        onKeyDown={e => e.key === 'Enter' && handleSendMessage(inputText, setInputText)}
                                        placeholder={loadedModel ? "Message Akitsu..." : "Load a model to start..."}
                                        style={{
                                            flex: 1, background: 'transparent', border: 'none',
                                            padding: '10px 0',
                                            color: dark ? 'rgba(255,255,255,0.88)' : '#1e293b',
                                            fontSize: '0.92rem', outline: 'none'
                                        }}
                                    />
                                    <AnimatePresence mode="wait">
                                        {isGenerating ? (
                                            <motion.button key="stop" initial={{ scale: 0.8 }} animate={{ scale: 1 }} exit={{ scale: 0.8 }}
                                                onClick={handleStopGeneration}
                                                style={{
                                                    width: '42px', height: '42px', borderRadius: '50%', flexShrink: 0,
                                                    background: 'linear-gradient(135deg, #ef4444, #dc2626)',
                                                    color: 'white', border: 'none', cursor: 'pointer',
                                                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                                                    boxShadow: '0 4px 16px rgba(239,68,68,0.45)'
                                                }}>
                                                <Square size={14} fill="white" />
                                            </motion.button>
                                        ) : (
                                            <motion.button key="send" initial={{ scale: 0.8 }} animate={{ scale: 1 }} exit={{ scale: 0.8 }}
                                                onClick={() => handleSendMessage(inputText, setInputText)}
                                                disabled={!inputText.trim() || !loadedModel}
                                                style={{
                                                    width: '42px', height: '42px', borderRadius: '50%', flexShrink: 0,
                                                    border: 'none',
                                                    background: (inputText.trim() && loadedModel)
                                                        ? 'linear-gradient(135deg, #818cf8, #38bdf8)'
                                                        : dark ? 'rgba(255,255,255,0.07)' : 'rgba(0,0,0,0.06)',
                                                    color: (inputText.trim() && loadedModel) ? 'white' : dark ? 'rgba(255,255,255,0.22)' : 'rgba(0,0,0,0.22)',
                                                    cursor: (inputText.trim() && loadedModel) ? 'pointer' : 'default',
                                                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                                                    boxShadow: (inputText.trim() && loadedModel) ? '0 4px 18px rgba(129,140,248,0.5)' : 'none',
                                                    transition: 'all 0.2s ease'
                                                }}>
                                                <Send size={16} style={{ transform: 'translateX(1px)' }} />
                                            </motion.button>
                                        )}
                                    </AnimatePresence>
                                </div>
                            </div>
                        </motion.div>
                    )}

                    {/* ── MODELS TAB ── */}
                    {activeTab === 'models' && (
                        <motion.div key="models" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }}
                            style={{ height: '100%', overflowY: 'auto', padding: '1.5rem' }} className="dashboard-scrollbar">
                            <div style={{
                                display: 'flex', flexDirection: 'column', gap: '0.8rem', marginBottom: '1.5rem',
                                padding: '1.05rem 1.1rem', borderRadius: '24px',
                                background: dark ? 'linear-gradient(180deg, rgba(15,23,42,0.76), rgba(17,24,39,0.82))' : 'rgba(255,255,255,0.88)',
                                border: `1px solid ${dark ? 'rgba(148,163,184,0.12)' : 'rgba(99,102,241,0.1)'}`,
                                boxShadow: dark ? '0 18px 38px rgba(2,6,23,0.24)' : '0 10px 28px rgba(99,102,241,0.06)'
                            }}>
                                <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                                    <div style={{
                                        width: 38, height: 38, borderRadius: '12px',
                                        background: dark ? 'rgba(59,130,246,0.14)' : 'rgba(99,102,241,0.1)',
                                        border: `1px solid ${dark ? 'rgba(96,165,250,0.18)' : 'rgba(99,102,241,0.15)'}`,
                                        display: 'flex', alignItems: 'center', justifyContent: 'center'
                                    }}>
                                        <Cpu size={18} color={dark ? '#93c5fd' : '#6366f1'} />
                                    </div>
                                    <div>
                                        <h2 style={{ margin: 0, fontSize: '1.08rem', fontWeight: 800, color: dark ? 'rgba(255,255,255,0.9)' : '#1e293b' }}>Model library</h2>
                                        <div style={{ fontSize: '0.78rem', marginTop: '0.2rem', color: dark ? 'rgba(226,232,240,0.5)' : '#64748b' }}>Honest local status, real bytes, cleaner control.</div>
                                    </div>
                                </div>
                                <div style={{ display: 'flex', gap: '0.65rem', flexWrap: 'wrap' }}>
                                    <div style={{ padding: '0.7rem 0.85rem', borderRadius: '18px', background: dark ? 'rgba(2,6,23,0.34)' : 'rgba(248,250,252,0.9)', border: `1px solid ${dark ? 'rgba(148,163,184,0.1)' : 'rgba(226,232,240,0.9)'}` }}>
                                        <div style={{ fontSize: '0.68rem', textTransform: 'uppercase', letterSpacing: '0.12em', fontWeight: 800, color: dark ? 'rgba(226,232,240,0.36)' : '#94a3b8' }}>Active</div>
                                        <div style={{ marginTop: '0.3rem', fontSize: '0.9rem', fontWeight: 800, color: dark ? '#e2e8f0' : '#1e293b' }}>{loadedModel || 'No model loaded'}</div>
                                    </div>
                                    <div style={{ padding: '0.7rem 0.85rem', borderRadius: '18px', background: dark ? 'rgba(2,6,23,0.34)' : 'rgba(248,250,252,0.9)', border: `1px solid ${dark ? 'rgba(148,163,184,0.1)' : 'rgba(226,232,240,0.9)'}` }}>
                                        <div style={{ fontSize: '0.68rem', textTransform: 'uppercase', letterSpacing: '0.12em', fontWeight: 800, color: dark ? 'rgba(226,232,240,0.36)' : '#94a3b8' }}>Stored models</div>
                                        <div style={{ marginTop: '0.3rem', fontSize: '0.9rem', fontWeight: 800, color: dark ? '#e2e8f0' : '#1e293b' }}>{models.filter((m: any) => m.status !== 'idle').length}</div>
                                    </div>
                                </div>
                            </div>
                            {isDetecting ? (
                                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '3rem', color: dark ? 'rgba(255,255,255,0.35)' : '#94a3b8', gap: '0.6rem' }}>
                                    <div className="spinner-small" style={{ borderColor: dark ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.1)', borderTopColor: dark ? '#a78bfa' : '#6366f1' }} />
                                    <span style={{ fontSize: '0.88rem' }}>Verifying local models...</span>
                                </div>
                            ) : (
                                <div style={{ display: 'grid', gridTemplateColumns: isMobile ? '1fr' : 'repeat(auto-fill, minmax(300px, 1fr))', gap: '1rem' }}>
                                    {models.map((m: any) => (
                                        <ModelCard key={m.id} model={m} dark={dark}
                                            onLoad={() => handleLoadModel(m, aiConfig)} onDownload={() => handleDownload(m)}
                                            onDelete={() => handleDelete(m)} onOffload={() => handleOffload()}
                                        />
                                    ))}
                                </div>
                            )}
                        </motion.div>
                    )}

                    {/* ── ENGINE TAB ── */}
                    {activeTab === 'settings' && (
                        <motion.div key="settings" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }}
                            style={{ height: '100%', overflowY: 'auto', padding: '1.5rem' }} className="dashboard-scrollbar">
                            <div style={{
                                display: 'flex', flexDirection: 'column', gap: '0.8rem', marginBottom: '1.5rem',
                                padding: '1.05rem 1.1rem', borderRadius: '24px',
                                background: dark ? 'linear-gradient(180deg, rgba(15,23,42,0.76), rgba(17,24,39,0.82))' : 'rgba(255,255,255,0.88)',
                                border: `1px solid ${dark ? 'rgba(148,163,184,0.12)' : 'rgba(99,102,241,0.1)'}`,
                                boxShadow: dark ? '0 18px 38px rgba(2,6,23,0.24)' : '0 10px 28px rgba(99,102,241,0.06)'
                            }}>
                                <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                                    <div style={{
                                        width: 38, height: 38, borderRadius: '12px',
                                        background: dark ? 'rgba(99,102,241,0.14)' : 'rgba(99,102,241,0.1)',
                                        border: `1px solid ${dark ? 'rgba(148,163,184,0.14)' : 'rgba(99,102,241,0.15)'}`,
                                        display: 'flex', alignItems: 'center', justifyContent: 'center'
                                    }}>
                                        <Settings size={18} color={dark ? '#c4b5fd' : '#6366f1'} />
                                    </div>
                                    <div>
                                        <h2 style={{ margin: 0, fontSize: '1.08rem', fontWeight: 800, color: dark ? 'rgba(255,255,255,0.9)' : '#1e293b' }}>Engine studio</h2>
                                        <div style={{ fontSize: '0.78rem', marginTop: '0.2rem', color: dark ? 'rgba(226,232,240,0.5)' : '#64748b' }}>Tune Akitsu for faster replies, lighter memory use, or fuller context.</div>
                                    </div>
                                </div>
                                <div style={{ display: 'flex', gap: '0.65rem', flexWrap: 'wrap' }}>
                                    <div style={{ padding: '0.7rem 0.85rem', borderRadius: '18px', background: dark ? 'rgba(2,6,23,0.34)' : 'rgba(248,250,252,0.9)', border: `1px solid ${dark ? 'rgba(148,163,184,0.1)' : 'rgba(226,232,240,0.9)'}` }}>
                                        <div style={{ fontSize: '0.68rem', textTransform: 'uppercase', letterSpacing: '0.12em', fontWeight: 800, color: dark ? 'rgba(226,232,240,0.36)' : '#94a3b8' }}>Preset</div>
                                        <div style={{ marginTop: '0.3rem', fontSize: '0.9rem', fontWeight: 800, color: dark ? '#e2e8f0' : '#1e293b' }}>{aiConfig.n_predict <= 128 ? 'Lite' : aiConfig.n_predict >= 512 ? 'Max' : 'Balanced'}</div>
                                    </div>
                                    <div style={{ padding: '0.7rem 0.85rem', borderRadius: '18px', background: dark ? 'rgba(2,6,23,0.34)' : 'rgba(248,250,252,0.9)', border: `1px solid ${dark ? 'rgba(148,163,184,0.1)' : 'rgba(226,232,240,0.9)'}` }}>
                                        <div style={{ fontSize: '0.68rem', textTransform: 'uppercase', letterSpacing: '0.12em', fontWeight: 800, color: dark ? 'rgba(226,232,240,0.36)' : '#94a3b8' }}>Threads</div>
                                        <div style={{ marginTop: '0.3rem', fontSize: '0.9rem', fontWeight: 800, color: dark ? '#e2e8f0' : '#1e293b' }}>{aiConfig.threads}</div>
                                    </div>
                                </div>
                            </div>
                            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.9rem', maxWidth: '600px' }}>

                                {/* Performance Preset */}
                                <div style={{ ...settingsCard, display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
                                    <div style={{ fontWeight: 700, fontSize: '0.9rem', color: dark ? 'rgba(255,255,255,0.8)' : '#1e293b' }}>Performance Preset</div>
                                    <div style={{ fontSize: '0.73rem', color: dark ? 'rgba(255,255,255,0.32)' : '#94a3b8' }}>Reload model after switching for full effect.</div>
                                    <div style={{ display: 'flex', gap: '8px' }}>
                                        {[
                                            { label: 'Lite', desc: 'Old device', cfg: { threads: 4, n_gpu_layers: 0, n_predict: 128, temperature: 0.4, top_k: 10, top_p: 0.8, penalty: 1.15, n_ctx: 768 } },
                                            { label: 'Balanced', desc: 'Default', cfg: { threads: 6, n_gpu_layers: 0, n_predict: 256, temperature: 0.5, top_k: 20, top_p: 0.85, penalty: 1.2, n_ctx: 1280 } },
                                            { label: 'Max', desc: 'New device', cfg: { threads: 6, n_gpu_layers: 0, n_predict: 512, temperature: 0.6, top_k: 40, top_p: 0.9, penalty: 1.1, n_ctx: 1280 } },
                                        ].map(({ label, desc, cfg }) => {
                                            const isActive = aiConfig.threads === cfg.threads && aiConfig.n_predict === cfg.n_predict && aiConfig.n_ctx === cfg.n_ctx;
                                            return (
                                                <button key={label} onClick={() => setAiConfig(prev => ({ ...prev, ...cfg }))} style={{
                                                    flex: 1, padding: '10px 4px', borderRadius: '12px', border: 'none', cursor: 'pointer',
                                                    fontWeight: 700, fontSize: '0.85rem',
                                                    background: isActive ? 'linear-gradient(135deg, #818cf8, #38bdf8)' : dark ? 'rgba(255,255,255,0.06)' : 'rgba(99,102,241,0.07)',
                                                    color: isActive ? 'white' : dark ? 'rgba(255,255,255,0.55)' : '#64748b',
                                                    boxShadow: isActive ? '0 4px 14px rgba(129,140,248,0.35)' : 'none',
                                                    display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '2px', transition: 'all 0.2s ease'
                                                }}>
                                                    <span>{label}</span>
                                                    <span style={{ fontSize: '0.63rem', opacity: 0.7, fontWeight: 400 }}>{desc}</span>
                                                </button>
                                            );
                                        })}
                                    </div>
                                </div>

                                {/* Direct Mode */}
                                <div style={{ ...settingsCard, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                                    <div>
                                        <div style={{ fontWeight: 700, fontSize: '0.9rem', color: dark ? 'rgba(255,255,255,0.8)' : '#1e293b' }}>Direct Mode</div>
                                        <div style={{ fontSize: '0.78rem', color: dark ? 'rgba(255,255,255,0.32)' : '#94a3b8', marginTop: '2px' }}>Bypass personality for maximum raw speed</div>
                                    </div>
                                    <button onClick={() => setAiConfig(prev => ({ ...prev, directMode: !prev.directMode }))} style={{
                                        padding: '6px 14px', borderRadius: '10px', border: 'none', fontWeight: 700, fontSize: '0.82rem', cursor: 'pointer',
                                        background: aiConfig.directMode ? 'linear-gradient(135deg, #22c55e, #16a34a)' : dark ? 'rgba(255,255,255,0.07)' : 'rgba(0,0,0,0.07)',
                                        color: aiConfig.directMode ? 'white' : dark ? 'rgba(255,255,255,0.4)' : '#94a3b8',
                                        boxShadow: aiConfig.directMode ? '0 4px 12px rgba(34,197,94,0.3)' : 'none'
                                    }}>{aiConfig.directMode ? 'ON' : 'OFF'}</button>
                                </div>

                                {/* Context RAG */}
                                <div style={{ ...settingsCard, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                                    <div>
                                        <div style={{ fontWeight: 700, fontSize: '0.9rem', color: dark ? 'rgba(255,255,255,0.8)' : '#1e293b' }}>Enable Context (RAG)</div>
                                        <div style={{ fontSize: '0.78rem', color: dark ? 'rgba(255,255,255,0.32)' : '#94a3b8', marginTop: '2px' }}>Read your notes and tasks</div>
                                    </div>
                                    <button onClick={() => setAiConfig(prev => ({ ...prev, disableContext: !prev.disableContext }))} style={{
                                        padding: '6px 14px', borderRadius: '10px', border: 'none', fontWeight: 700, fontSize: '0.82rem', cursor: 'pointer',
                                        background: !aiConfig.disableContext ? 'linear-gradient(135deg, #818cf8, #38bdf8)' : dark ? 'rgba(255,255,255,0.07)' : 'rgba(0,0,0,0.07)',
                                        color: !aiConfig.disableContext ? 'white' : dark ? 'rgba(255,255,255,0.4)' : '#94a3b8',
                                        boxShadow: !aiConfig.disableContext ? '0 4px 12px rgba(129,140,248,0.3)' : 'none'
                                    }}>{!aiConfig.disableContext ? 'ON' : 'OFF'}</button>
                                </div>

                                {/* CPU Threads */}
                                <div style={{ ...settingsCard, display: 'flex', flexDirection: 'column', gap: '0.6rem' }}>
                                    <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                                        <div style={{ fontWeight: 700, fontSize: '0.9rem', color: dark ? 'rgba(255,255,255,0.8)' : '#1e293b' }}>CPU Threads</div>
                                        <div style={{ fontWeight: 900, color: dark ? '#38bdf8' : '#0ea5e9', fontSize: '0.95rem' }}>{aiConfig.threads}</div>
                                    </div>
                                    <input type="range" min="1" max="16" value={aiConfig.threads} onChange={e => setAiConfig(prev => ({ ...prev, threads: parseInt(e.target.value) }))} style={{ width: '100%' }} />
                                </div>

                                {/* GPU Layers */}
                                <div style={{ ...settingsCard, display: 'flex', flexDirection: 'column', gap: '0.6rem' }}>
                                    <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                                        <div style={{ fontWeight: 700, fontSize: '0.9rem', color: dark ? 'rgba(255,255,255,0.8)' : '#1e293b' }}>GPU Layers (VRAM)</div>
                                        <div style={{ fontWeight: 900, color: '#22c55e', fontSize: '0.95rem' }}>{aiConfig.n_gpu_layers}</div>
                                    </div>
                                    <input type="range" min="0" max="35" value={aiConfig.n_gpu_layers} onChange={e => setAiConfig(prev => ({ ...prev, n_gpu_layers: parseInt(e.target.value) }))} style={{ width: '100%' }} />
                                    <div style={{ fontSize: '0.7rem', color: dark ? 'rgba(255,255,255,0.28)' : '#94a3b8' }}>For 1.5B models keep at 0 — partial GPU offload (e.g. 10/28 layers) is slower due to CPU↔GPU sync. Use max (28+) or 0. Reload model to apply.</div>
                                </div>

                                {/* Context Window */}
                                <div style={{ ...settingsCard, display: 'flex', flexDirection: 'column', gap: '0.6rem' }}>
                                    <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                                        <div style={{ fontWeight: 700, fontSize: '0.9rem', color: dark ? 'rgba(255,255,255,0.8)' : '#1e293b' }}>Context Window</div>
                                        <div style={{ fontWeight: 900, color: dark ? '#f59e0b' : '#d97706', fontSize: '0.95rem' }}>{aiConfig.n_ctx} tok</div>
                                    </div>
                                    <input type="range" min="512" max="2048" step="128" value={aiConfig.n_ctx} onChange={e => setAiConfig(prev => ({ ...prev, n_ctx: parseInt(e.target.value) }))} style={{ width: '100%' }} />
                                    <div style={{ fontSize: '0.7rem', color: dark ? 'rgba(255,255,255,0.28)' : '#94a3b8' }}>Lower = faster decode. 768 old devices, 1280+ new. Reload to apply.</div>
                                </div>

                            </div>
                        </motion.div>
                    )}
                </AnimatePresence>
            </main>

            {/* History drawer */}
            <AnimatePresence>
                {isHistoryOpen && (
                    <>
                        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
                            onClick={() => setIsHistoryOpen(false)}
                            style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.6)', backdropFilter: 'blur(6px)', zIndex: 100 }} />
                        <motion.div initial={{ x: '100%' }} animate={{ x: 0 }} exit={{ x: '100%' }}
                            style={{
                                position: 'fixed', top: 0, right: 0, bottom: 0, width: 'min(300px, 85vw)',
                                background: dark ? 'rgba(8,12,20,0.97)' : 'rgba(255,255,255,0.97)',
                                backdropFilter: 'blur(24px)', WebkitBackdropFilter: 'blur(24px)',
                                zIndex: 101, display: 'flex', flexDirection: 'column',
                                borderLeft: `1px solid ${dark ? 'rgba(129,140,248,0.12)' : 'rgba(99,102,241,0.1)'}`
                            }}>
                            <div style={{
                                padding: '1.2rem 1.4rem', borderBottom: `1px solid ${dark ? 'rgba(255,255,255,0.06)' : 'rgba(99,102,241,0.08)'}`,
                                display: 'flex', justifyContent: 'space-between', alignItems: 'center'
                            }}>
                                <h2 style={{ margin: 0, fontSize: '1rem', fontWeight: 800, color: dark ? 'rgba(255,255,255,0.85)' : '#1e293b' }}>History</h2>
                                <button onClick={() => setIsHistoryOpen(false)} style={{
                                    background: dark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.05)',
                                    border: 'none', borderRadius: '8px', padding: '6px',
                                    color: dark ? 'rgba(255,255,255,0.5)' : '#94a3b8', cursor: 'pointer', display: 'flex'
                                }}>
                                    <X size={18} />
                                </button>
                            </div>
                            <div style={{ flex: 1, overflowY: 'auto', padding: '0.75rem' }} className="dashboard-scrollbar">
                                {sessions.map(s => (
                                    <div key={s.id} onClick={() => handleSwitchSession(s.id)} style={{
                                        padding: '10px 12px', borderRadius: '12px', marginBottom: '6px', cursor: 'pointer',
                                        display: 'flex', justifyContent: 'space-between', alignItems: 'center',
                                        background: activeSessionId === s.id
                                            ? dark ? 'rgba(129,140,248,0.12)' : 'rgba(99,102,241,0.08)'
                                            : 'transparent',
                                        border: `1px solid ${activeSessionId === s.id ? dark ? 'rgba(129,140,248,0.18)' : 'rgba(99,102,241,0.12)' : 'transparent'}`
                                    }}>
                                        <div style={{ fontWeight: 600, fontSize: '0.87rem', color: dark ? 'rgba(255,255,255,0.75)' : '#374151', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', flex: 1 }}>{s.title}</div>
                                        <button onClick={(e) => handleDeleteSession(s.id, e)} style={{
                                            background: 'transparent', border: 'none', color: dark ? 'rgba(239,68,68,0.6)' : '#ef4444',
                                            cursor: 'pointer', padding: '2px', flexShrink: 0
                                        }}>
                                            <X size={15} />
                                        </button>
                                    </div>
                                ))}
                            </div>
                        </motion.div>
                    </>
                )}
            </AnimatePresence>
        </motion.div>
    );
};

const formatBytes = (bytes?: number) => {
    if (!bytes || bytes <= 0) return null;
    const units = ['B', 'KB', 'MB', 'GB'];
    let value = bytes;
    let unitIndex = 0;
    while (value >= 1024 && unitIndex < units.length - 1) {
        value /= 1024;
        unitIndex += 1;
    }
    return `${value.toFixed(unitIndex >= 2 ? 1 : 0)} ${units[unitIndex]}`;
};

const getDownloadLabel = (model: any) => {
    if (model.status === 'loaded') return 'Ready';
    if (model.status === 'loading') return 'Loading';
    if (model.status === 'downloaded') return 'Downloaded';
    if (model.status !== 'downloading') return 'Available';
    if (model.downloadStatus === 1) return 'Queued';
    if (model.downloadStatus === 2) return 'Downloading';
    if (model.downloadStatus === 4) return 'Paused';
    return 'Preparing';
};

const getDownloadMeta = (model: any) => {
    const downloaded = formatBytes(model.bytesDownloaded);
    const total = formatBytes(model.bytesTotal);
    if (model.status !== 'downloading') return downloaded && total ? `${downloaded} stored` : 'Ready for use';
    if (model.downloadStatus === 1) return 'Queued and waiting for Android downloader';
    if (model.downloadStatus === 4) return 'Paused by the system';
    if (downloaded && total) return `${downloaded} / ${total}`;
    if (downloaded) return `${downloaded} received`;
    return 'Waiting for size info';
};

const TabButton = ({ active, onClick, icon: Icon, label, dark }: any) => (
    <motion.button
        whileTap={{ scale: 0.97 }}
        onClick={onClick}
        style={{
            display: 'flex', alignItems: 'center', gap: '8px', padding: active ? '9px 14px' : '9px 12px',
            borderRadius: '14px', border: 'none',
            background: active
                ? dark ? 'linear-gradient(135deg, rgba(99,102,241,0.26), rgba(56,189,248,0.18))' : 'rgba(99,102,241,0.1)'
                : 'transparent',
            color: active ? (dark ? '#e2e8f0' : '#4338ca') : (dark ? 'rgba(226,232,240,0.52)' : '#94a3b8'),
            cursor: 'pointer', fontWeight: 700, fontSize: '0.82rem', transition: 'all 0.18s ease', position: 'relative'
        }}
    >
        {active && (
            <span style={{
                position: 'absolute', inset: 0, borderRadius: 'inherit',
                border: `1px solid ${dark ? 'rgba(148,163,184,0.14)' : 'rgba(99,102,241,0.12)'}`,
                boxShadow: dark ? 'inset 0 1px 0 rgba(255,255,255,0.05)' : 'none'
            }} />
        )}
        <Icon size={15} />
        <span>{label}</span>
    </motion.button>
);

const SummaryCard = ({
    dark,
    contextLabel,
    digest,
    noteCount,
    isRefreshing,
    needsRefresh,
    chargingMessage,
    onRefresh,
    onChat
}: {
    dark: boolean;
    contextLabel: string;
    digest?: SummaryDigest;
    noteCount: number;
    isRefreshing: boolean;
    needsRefresh: boolean;
    chargingMessage: string;
    onRefresh: () => void;
    onChat: () => void;
}) => {
    const accent = contextLabel.toLowerCase().includes('week')
        ? {
            border: dark ? 'rgba(125, 211, 252, 0.2)' : 'rgba(56, 189, 248, 0.18)',
            badgeBg: dark ? 'rgba(56, 189, 248, 0.14)' : 'rgba(224, 242, 254, 0.92)',
            badgeText: dark ? '#bae6fd' : '#0369a1',
            chipBg: dark ? 'rgba(56,130,246,0.16)' : 'rgba(219, 234, 254, 0.95)',
            chipText: dark ? '#bfdbfe' : '#1d4ed8',
            glow: dark ? 'radial-gradient(circle, rgba(56,189,248,0.16), transparent 68%)' : 'radial-gradient(circle, rgba(125,211,252,0.3), transparent 68%)',
            buttonBg: dark ? 'linear-gradient(135deg, #38bdf8, #60a5fa)' : 'linear-gradient(135deg, #0ea5e9, #3b82f6)'
        }
        : {
            border: dark ? 'rgba(244, 114, 182, 0.18)' : 'rgba(251, 113, 133, 0.16)',
            badgeBg: dark ? 'rgba(244, 114, 182, 0.14)' : 'rgba(255, 228, 230, 0.94)',
            badgeText: dark ? '#fbcfe8' : '#be185d',
            chipBg: dark ? 'rgba(236,72,153,0.14)' : 'rgba(255, 241, 242, 0.98)',
            chipText: dark ? '#f9a8d4' : '#be123c',
            glow: dark ? 'radial-gradient(circle, rgba(244,114,182,0.14), transparent 68%)' : 'radial-gradient(circle, rgba(251,113,133,0.22), transparent 68%)',
            buttonBg: dark ? 'linear-gradient(135deg, #f472b6, #fb7185)' : 'linear-gradient(135deg, #ec4899, #f43f5e)'
        };

    return (
    <div style={{
        padding: '1.05rem',
        borderRadius: '28px',
        background: dark
            ? 'linear-gradient(180deg, rgba(15,23,42,0.92), rgba(17,24,39,0.84))'
            : 'linear-gradient(180deg, rgba(255,255,255,0.98), rgba(248,250,255,0.96) 52%, rgba(252,247,255,0.98) 100%)',
        border: `1px solid ${accent.border}`,
        boxShadow: dark ? '0 18px 40px rgba(2,6,23,0.28)' : '0 18px 42px rgba(148,163,184,0.14)',
        display: 'flex',
        flexDirection: 'column',
        gap: '0.9rem',
        position: 'relative',
        overflow: 'hidden',
        backdropFilter: 'blur(18px)',
        WebkitBackdropFilter: 'blur(18px)'
    }}>
        <div style={{
            position: 'absolute',
            top: '-3rem',
            right: '-2rem',
            width: '10rem',
            height: '10rem',
            borderRadius: '999px',
            background: accent.glow,
            filter: 'blur(8px)',
            pointerEvents: 'none'
        }} />
        <div style={{
            position: 'absolute',
            bottom: '-4rem',
            left: '-3rem',
            width: '9rem',
            height: '9rem',
            borderRadius: '999px',
            background: dark ? 'radial-gradient(circle, rgba(255,255,255,0.05), transparent 70%)' : 'radial-gradient(circle, rgba(255,255,255,0.85), transparent 72%)',
            pointerEvents: 'none'
        }} />
        <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: '0.9rem' }}>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.4rem', position: 'relative', zIndex: 1 }}>
                <div style={{
                    display: 'inline-flex',
                    alignItems: 'center',
                    gap: '0.45rem',
                    fontSize: '0.75rem',
                    fontWeight: 800,
                    letterSpacing: '0.08em',
                    textTransform: 'uppercase',
                    color: accent.badgeText,
                    padding: '0.42rem 0.7rem',
                    borderRadius: '999px',
                    background: accent.badgeBg,
                    width: 'fit-content'
                }}>
                    <CalendarRange size={14} />
                    {contextLabel}
                </div>
                <div style={{ fontSize: '1.04rem', fontWeight: 800, color: dark ? '#f8fafc' : '#172033', letterSpacing: '-0.02em' }}>
                    {digest?.title || `${contextLabel} Summary`}
                </div>
            </div>
            <div style={{
                padding: '0.42rem 0.65rem',
                borderRadius: '999px',
                background: needsRefresh
                    ? (dark ? 'rgba(251, 191, 36, 0.14)' : 'rgba(254, 249, 195, 0.98)')
                    : (dark ? 'rgba(74, 222, 128, 0.14)' : 'rgba(220, 252, 231, 0.98)'),
                color: needsRefresh ? '#d97706' : '#15803d',
                fontSize: '0.73rem',
                fontWeight: 800,
                position: 'relative',
                zIndex: 1
            }}>
                {needsRefresh ? 'Needs refresh' : 'Ready'}
            </div>
        </div>

        <div style={{ color: dark ? 'rgba(226,232,240,0.72)' : '#64748b', fontSize: '0.82rem', lineHeight: 1.6, position: 'relative', zIndex: 1 }}>
            {noteCount === 0 ? 'No notes were updated in this window yet.' : `${noteCount} note${noteCount === 1 ? '' : 's'} included.`}
            {digest?.generatedAt ? ` Updated ${new Date(digest.generatedAt).toLocaleString([], { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })}.` : ''}
        </div>

        <div style={{
            padding: '1rem',
            borderRadius: '20px',
            background: dark ? 'rgba(2,6,23,0.34)' : 'rgba(255,255,255,0.78)',
            color: dark ? 'rgba(241,245,249,0.92)' : '#334155',
            lineHeight: 1.7,
            fontSize: '0.88rem',
            minHeight: '7.6rem',
            border: `1px solid ${dark ? 'rgba(148,163,184,0.08)' : 'rgba(255,255,255,0.8)'}`,
            boxShadow: dark ? 'inset 0 1px 0 rgba(255,255,255,0.03)' : 'inset 0 1px 0 rgba(255,255,255,0.95)',
            position: 'relative',
            zIndex: 1
        }}>
            {digest?.summary || 'Akitsu can prepare a concise readymade summary here so you can skim first and chat only when needed.'}
        </div>

        {digest?.highlights && digest.highlights.length > 0 && (
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.45rem', position: 'relative', zIndex: 1 }}>
                {digest.highlights.map((item, index) => (
                    <span key={`${item}-${index}`} style={{
                        padding: '0.42rem 0.62rem',
                        borderRadius: '999px',
                        background: accent.chipBg,
                        color: accent.chipText,
                        fontSize: '0.74rem',
                        fontWeight: 700
                    }}>
                        {item}
                    </span>
                ))}
            </div>
        )}

        <div style={{ color: dark ? 'rgba(148,163,184,0.76)' : '#7c8aa5', fontSize: '0.78rem', lineHeight: 1.55, position: 'relative', zIndex: 1 }}>
            {chargingMessage}
        </div>

        <div style={{ display: 'flex', gap: '0.65rem', flexWrap: 'wrap', position: 'relative', zIndex: 1 }}>
            <button onClick={onChat} style={{
                padding: '0.78rem 1rem',
                borderRadius: '999px',
                border: 'none',
                background: accent.buttonBg,
                color: 'white',
                fontWeight: 800,
                cursor: 'pointer',
                boxShadow: dark ? '0 10px 20px rgba(15,23,42,0.24)' : '0 10px 20px rgba(99,102,241,0.16)'
            }}>
                Chat with Akitsu
            </button>
            <button onClick={onRefresh} disabled={isRefreshing} style={{
                padding: '0.78rem 1rem',
                borderRadius: '999px',
                border: `1px solid ${dark ? 'rgba(148,163,184,0.14)' : 'rgba(203,213,225,0.9)'}`,
                background: dark ? 'rgba(15,23,42,0.72)' : 'rgba(255,255,255,0.88)',
                color: dark ? '#e2e8f0' : '#334155',
                fontWeight: 800,
                cursor: isRefreshing ? 'default' : 'pointer',
                display: 'inline-flex',
                alignItems: 'center',
                gap: '0.45rem',
                opacity: isRefreshing ? 0.7 : 1,
                boxShadow: dark ? 'inset 0 1px 0 rgba(255,255,255,0.03)' : 'inset 0 1px 0 rgba(255,255,255,0.96)'
            }}>
                {isRefreshing ? <RefreshCw size={14} /> : <Zap size={14} />}
                {isRefreshing ? 'Summarising' : (digest ? 'Summarise again' : 'Summarise now')}
            </button>
        </div>
    </div>
    );
};

const ModelCard = ({ model, onLoad, onDownload, onDelete, onOffload, dark }: any) => {
    const progress = typeof model.progress === 'number' ? Math.max(0, Math.min(1, model.progress)) : 0;
    const progressPercent = Math.round(progress * 100);
    const downloadLabel = getDownloadLabel(model);
    const downloadMeta = getDownloadMeta(model);
    const accent = model.status === 'loaded'
        ? '#22c55e'
        : model.status === 'downloading'
            ? '#60a5fa'
            : dark ? '#c7d2fe' : '#6366f1';

    return (
        <motion.div
            layout
            whileHover={{ y: dark ? -2 : -3 }}
            style={{
                background: dark ? 'linear-gradient(180deg, rgba(15,23,42,0.82), rgba(17,24,39,0.88))' : 'rgba(255,255,255,0.95)',
                padding: '1.15rem', borderRadius: '26px',
                border: `1px solid ${dark ? 'rgba(148,163,184,0.12)' : 'rgba(99,102,241,0.12)'}`,
                display: 'flex', flexDirection: 'column', gap: '0.95rem', minHeight: '230px',
                boxShadow: dark ? '0 22px 46px rgba(2,6,23,0.28)' : '0 10px 30px rgba(99,102,241,0.08)',
                backdropFilter: 'blur(18px)', WebkitBackdropFilter: 'blur(18px)', overflow: 'hidden', position: 'relative'
            }}
        >
            <div style={{
                position: 'absolute', top: '-40px', right: '-30px', width: '150px', height: '150px', borderRadius: '50%',
                background: dark ? 'radial-gradient(circle, rgba(59,130,246,0.13), transparent 68%)' : 'radial-gradient(circle, rgba(129,140,248,0.1), transparent 68%)',
                filter: 'blur(8px)', pointerEvents: 'none'
            }} />

            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: '0.8rem', position: 'relative', zIndex: 1 }}>
                <div style={{ display: 'flex', flexDirection: 'column', gap: '0.45rem' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.45rem' }}>
                        <span style={{ width: 9, height: 9, borderRadius: '50%', background: accent, boxShadow: `0 0 18px ${accent}33` }} />
                        <span style={{ fontSize: '0.68rem', letterSpacing: '0.14em', textTransform: 'uppercase', fontWeight: 800, color: dark ? 'rgba(226,232,240,0.42)' : '#64748b' }}>
                            {model.status === 'loaded' ? 'Active model' : 'Local model'}
                        </span>
                    </div>
                    <h3 style={{ margin: 0, fontSize: '1.02rem', fontWeight: 800, color: dark ? 'rgba(255,255,255,0.92)' : '#1e293b' }}>{model.name}</h3>
                    <p style={{ margin: 0, fontSize: '0.8rem', color: dark ? 'rgba(226,232,240,0.58)' : '#64748b', lineHeight: 1.5 }}>{model.description}</p>
                </div>
                <span style={{
                    fontSize: '0.65rem', fontWeight: 800, padding: '0.42rem 0.78rem', borderRadius: '999px',
                    background: model.status === 'loaded'
                        ? 'rgba(34,197,94,0.14)'
                        : model.status === 'downloading'
                            ? dark ? 'rgba(96,165,250,0.16)' : 'rgba(99,102,241,0.08)'
                            : dark ? 'rgba(255,255,255,0.06)' : 'rgba(99,102,241,0.08)',
                    color: accent,
                    border: `1px solid ${dark ? 'rgba(148,163,184,0.1)' : 'transparent'}`
                }}>{downloadLabel}</span>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, minmax(0, 1fr))', gap: '0.7rem', position: 'relative', zIndex: 1 }}>
                <div style={{ padding: '0.8rem', borderRadius: '18px', background: dark ? 'rgba(2,6,23,0.36)' : 'rgba(248,250,252,0.9)', border: `1px solid ${dark ? 'rgba(148,163,184,0.1)' : 'rgba(226,232,240,0.9)'}` }}>
                    <div style={{ fontSize: '0.67rem', textTransform: 'uppercase', letterSpacing: '0.12em', fontWeight: 800, color: dark ? 'rgba(226,232,240,0.36)' : '#94a3b8' }}>Size</div>
                    <div style={{ marginTop: '0.35rem', fontSize: '0.96rem', fontWeight: 800, color: dark ? 'rgba(255,255,255,0.88)' : '#1e293b' }}>{model.size}</div>
                </div>
                <div style={{ padding: '0.8rem', borderRadius: '18px', background: dark ? 'rgba(2,6,23,0.36)' : 'rgba(248,250,252,0.9)', border: `1px solid ${dark ? 'rgba(148,163,184,0.1)' : 'rgba(226,232,240,0.9)'}` }}>
                    <div style={{ fontSize: '0.67rem', textTransform: 'uppercase', letterSpacing: '0.12em', fontWeight: 800, color: dark ? 'rgba(226,232,240,0.36)' : '#94a3b8' }}>Storage</div>
                    <div style={{ marginTop: '0.35rem', fontSize: '0.96rem', fontWeight: 800, color: dark ? 'rgba(255,255,255,0.88)' : '#1e293b' }}>{model.status === 'idle' ? 'Not saved' : (formatBytes(model.bytesTotal || model.bytesDownloaded) || 'Local')}</div>
                </div>
            </div>

            <div style={{ position: 'relative', zIndex: 1, display: 'flex', flexDirection: 'column', gap: '0.6rem', marginTop: '0.15rem' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '0.75rem' }}>
                    <span style={{ fontSize: '0.78rem', fontWeight: 700, color: dark ? 'rgba(226,232,240,0.82)' : '#334155' }}>{downloadLabel}</span>
                    <span style={{ fontSize: '0.78rem', fontWeight: 800, color: accent }}>
                        {model.status === 'downloading'
                            ? (model.bytesTotal ? `${progressPercent}%` : (model.downloadStatus === 1 ? 'Queued' : 'Waiting'))
                            : model.status === 'loaded'
                                ? 'Loaded'
                                : model.status === 'downloaded'
                                    ? 'Ready'
                                    : 'Remote'}
                    </span>
                </div>
                <div style={{ height: '10px', borderRadius: '999px', background: dark ? 'rgba(255,255,255,0.08)' : 'rgba(99,102,241,0.08)', overflow: 'hidden' }}>
                    <motion.div
                        animate={{ width: `${model.status === 'idle' ? 0 : progress * 100}%` }}
                        transition={{ duration: 0.25, ease: 'easeOut' }}
                        style={{
                            width: `${model.status === 'idle' ? 0 : progress * 100}%`, height: '100%', borderRadius: 'inherit',
                            background: model.status === 'loaded'
                                ? 'linear-gradient(135deg, #22c55e, #16a34a)'
                                : 'linear-gradient(135deg, #6366f1, #38bdf8)'
                        }}
                    />
                </div>
                <div style={{ fontSize: '0.72rem', color: dark ? 'rgba(226,232,240,0.56)' : '#64748b', minHeight: '1rem' }}>{downloadMeta}</div>
            </div>

            <div style={{ display: 'flex', gap: '8px', marginTop: 'auto', position: 'relative', zIndex: 1 }}>
                {model.status === 'idle' && <button onClick={onDownload} style={{ flex: 1, padding: '10px', borderRadius: '16px', background: 'linear-gradient(135deg, #6366f1, #0ea5e9)', color: 'white', border: 'none', fontWeight: 700, fontSize: '0.85rem', boxShadow: '0 8px 18px rgba(99,102,241,0.3)' }}>Download model</button>}
                {model.status === 'downloading' && <button disabled style={{ flex: 1, padding: '10px', borderRadius: '16px', background: dark ? 'rgba(59,130,246,0.14)' : 'rgba(99,102,241,0.08)', color: dark ? '#bfdbfe' : '#4f46e5', border: `1px solid ${dark ? 'rgba(96,165,250,0.14)' : 'transparent'}`, fontWeight: 700, fontSize: '0.85rem' }}>{downloadLabel}</button>}
                {model.status === 'downloaded' && <button onClick={onLoad} style={{ flex: 1, padding: '10px', borderRadius: '16px', background: 'linear-gradient(135deg, #22c55e, #16a34a)', color: 'white', border: 'none', fontWeight: 700, fontSize: '0.85rem', boxShadow: '0 8px 18px rgba(34,197,94,0.22)' }}>Load in Akitsu</button>}
                {model.status === 'loaded' && <button onClick={onOffload} style={{ flex: 1, padding: '10px', borderRadius: '16px', background: dark ? 'rgba(239,68,68,0.12)' : 'rgba(239,68,68,0.1)', color: '#f87171', border: '1px solid rgba(248,113,113,0.22)', fontWeight: 700, fontSize: '0.85rem' }}>Offload model</button>}
                <button onClick={onDelete} style={{ background: dark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.05)', border: `1px solid ${dark ? 'rgba(148,163,184,0.08)' : 'transparent'}`, padding: '10px', borderRadius: '16px', color: dark ? 'rgba(255,255,255,0.48)' : '#94a3b8', cursor: 'pointer' }}>
                    <X size={16} />
                </button>
            </div>
        </motion.div>
    );
};

const TypingIndicator = ({ isThinking, dark }: any) => (
    <motion.div initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} style={{
        padding: '12px 16px',
        background: dark ? 'rgba(15,23,42,0.62)' : 'rgba(255,255,255,0.95)',
        borderRadius: '20px 20px 20px 5px',
        border: `1px solid ${dark ? 'rgba(167,139,250,0.13)' : 'rgba(99,102,241,0.12)'}`,
        width: 'fit-content',
        boxShadow: dark ? '0 12px 24px rgba(2,6,23,0.22)' : '0 4px 18px rgba(0,0,0,0.06)'
    }}>
        <div style={{ display: 'flex', gap: '5px', alignItems: 'center' }}>
            {[0, 1, 2].map(i => (
                <motion.div key={i}
                    animate={{ scale: [1, 1.45, 1], opacity: [0.35, 1, 0.35] }}
                    transition={{ repeat: Infinity, duration: 0.85, delay: i * 0.17 }}
                    style={{
                        width: 7, height: 7, borderRadius: '50%',
                        background: dark ? 'linear-gradient(135deg, #a78bfa, #38bdf8)' : '#6366f1'
                    }}
                />
            ))}
            {isThinking && <span style={{ fontSize: '0.69rem', color: dark ? 'rgba(255,255,255,0.3)' : '#94a3b8', marginLeft: '5px' }}>thinking...</span>}
        </div>
    </motion.div>
);

export default AIView;
